### ISSUE TITLE
Some overlapping functionality

### ISSUE THREAD

**Issue by camilogarciabotero** [mashu/EvolutionModels.jl#1]
Hey there @mashu 

I am always really exited when spotting a new bioinformatic Julia package. This package reminded me the good old [SubstitutionModels.jl](https://github.com/BioJulia/SubstitutionModels.jl). 

I think there are some overlaps, although your idea of having some distance calculations and other evolutionary stuff is very cool. Why not leverage on that to improve the evolutionary metrics?

**Comment by mashu** [comment]
Hi @camilogarciabotero ! 

Thanks for your interest! I created this package mainly because I needed empirical protein models and FastTree-compatible distance calculations (-makematrix). While SubstitutionModels.jl is great, I wanted to keep this very minimal with optional features and conditional compilation. Though it's still experimental (as noted in the README), I'm definitely open to contributing protein-related functionality to SubstitutionModels.jl if that would be more useful for the community. This was mostly a playground project, which is why I haven't registered it yet. For the simulation and tree building there is MolecularEvolution.jl.

**Comment by camilogarciabotero** [comment]
Ah, I see. I’m not actively using this right now (though I did explore a bit…), but I just wanted to mention those other efforts 😊. I thought it might be helpful to align our work and avoid any duplication of effort in the BioJulia
